### ISSUE TITLE
[BUG]Some of the sites missing in the report for workflow scanner

### ISSUE THREAD

**Issue by BalakrishnaDuggireddy** [pnp/modernization#604]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Modernization Scanner: something went wrong...: Some of the sites in the tenant are not scanned by modernization scanner.

#### Expected or Desired Behavior

The modernization scanner should be able to scan all the sites in the tenant.

#### Observed Behavior

I ran this scanner to detect the workflows. some of the sites have workflows but they are not shown in the report.

#### Steps to Reproduce

There are no errors. however the sites are not shown in the workflow scanner report.

**Comment by jansenbe** [comment]
Can you provide more context about the workflows you think should have been detected? Are they missing at sub site level or for the complete site collection? Do note that for example workflows attached to a content type only show at the root site where the content type is defined, not at each site/list using the content types in question. The scanner does this to avoid generating a lot of duplicate entries for a single source workflow. Also assume you're scanning for SharePoint 2013 workflows?

**Comment by BalakrishnaDuggireddy** [comment]
Thanks for your response Bert. I noticed that all the sites in the tenant are not scanning. i ran the scanner in June and some of the sites were missing in the report. i ran the scan again this month and the sites which were missing in the June month report can see this month report. The missing sites having SP 2010 list workflow. the thing is that don't see those missing sites in the ModernizationSiteScanResults report also and not in errors report.
i'm scanning for SP2010 workflows.

**Comment by jansenbe** [comment]
Closing as WF2010 retirement has been handled.
