### ISSUE TITLE
On-Premises cannot use new PnP.PowerShell (legacy not up to date with latest fixes)

### ISSUE THREAD

**Issue by stact** [pnp/modernization#609]
Page header not set and some switch not available on legacy PnP PowerShell
I tried to use PnP.PowerShell module to get latest version, but I've some trouble on onpremise authentication (403 forbidden)

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Need to migrate on premises pages  site to modern (online tenant).
Header image need to be set with "PublishingRollupImage" field.
Content need to be migrated with web part and content mapping.

#### Observed Behavior
The content is migrated as expected but header can't be set dynamically (StaticString works well)
```xml
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
```
No errors on logs, no additional information about the header
NB: The image exists in source and destination library on the same site.

#### Steps to Reproduce
1. Install legacy version of PnP PowerShell
`Install-Module -Name SharePointPnPPowerShellOnline -Scope CurrentUser`
2. Migrate publishing page with ConvertTo-PnPClientSidePage from SP2016 or SP2019 to SharePoint online site
3. Check site on SharePoint online

Thank you for your help!

**Comment by stact** [comment]
Got the problem. Set header doesn't like %20 for file spaces. We need to remove the %20 and let the spaces blank

**Comment by stact** [comment]
Does someone have a procedure to use the last version of PnP.PowerShell to works on SP2016 and/or SP2019?
When I'm using ConvertTo-PnP we have 403 forbidden also on Get-PnPWeb

Thank you for your help!

**Comment by jansenbe** [comment]
@stact :  Did you manage to solve your issue? If not then please create a new issue in the PnP Framework repo, will close this one.
