### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zwelding** [pnp/modernization#610]
#### Problem Area

I am trying to transform pages that were copied to online from a SP2013 farm. They were migrated properly to online and are publishing pages. Some pages are failing with a non specific error. I am not sure where to look. HELP!

Summary
9/20/2021 11:52:30 AM | 00:00:02 | /office/purchasing/electronics-authorization/Pages/default.aspx |   | A issue prevented successful transformation 

Errors During Transformation
9/20/2021 11:52:33 AM | /office/purchasing/electronics-authorization/Pages/default.aspx | Web Part Mapping | An error occurred processing functions - Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

Critical Errors during transformation
9/20/2021 11:52:33 AM - /office/purchasing/electronics-authorization/Pages/default.aspx
Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at PnP.Framework.Modernization.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo methodInfo) at PnP.Framework.Modernization.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, Property property) at PnP.Framework.Modernization.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart) at PnP.Framework.Modernization.Transform.ContentTransformator.Transform(List`1 webParts) at PnP.Framework.Modernization.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)

Transformation Details: /office/purchasing/electronics-authorization/Pages/default.aspx
Report date: 9/20/2021 11:55:17 AM
Transform duration: 00:00:02
Transforming from site: https://dakotamn.sharepoint.com/sites/DCWorksStage/office/purchasing/electronics-authorization
Cross-Site transfer mode to site: https://dakotamn.sharepoint.com/Office/Purchasing/electronics-authorization
Transforming page: /sites/DCWorksStage/office/purchasing/electronics-authorization/Pages/default.aspx
Source SharePoint version: Online (16.0.0.21708)
Mode: Publishing Page Transformation Mode
A critical error occurred - transformation did not complete

9/20/2021 11:52:30 AM | Input Validation | Validation checks complete
-- | -- | --
9/20/2021 11:52:30 AM | SharePoint Connection | Loading client context objects
9/20/2021 11:52:30 AM | SharePoint Connection | Loading target client context object
9/20/2021 11:52:31 AM | Page Creation | Detect if the page is living inside a folder
9/20/2021 11:52:31 AM | Page Creation | Just try to load the page in the fastest possible manner, we only want to see if the page exists or not
9/20/2021 11:52:31 AM | Load | Page does not exist in current web
9/20/2021 11:52:31 AM | Page Creation | Checking Page Exists
9/20/2021 11:52:32 AM | Page Creation | Modern page created
9/20/2021 11:52:32 AM | Article page handling | Transforming source page as Article page
9/20/2021 11:52:32 AM | Article page handling | Recognized source page as a Publishing Page - Analyzing web parts and page layouts
9/20/2021 11:52:32 AM | Page Layout Manager | Page uses Summary_Links.BT as page layout, mapping that will be used is Summary_Links.BT
9/20/2021 11:52:32 AM | Article page handling | Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
9/20/2021 11:52:32 AM | Set Page Title | Setting the modern page title: Electronics Authorization
9/20/2021 11:52:32 AM | Article page handling | Preparing content transformation
9/20/2021 11:52:32 AM | Article page handling | Transforming content
9/20/2021 11:52:32 AM | Content Transform | Transforming web parts
9/20/2021 11:52:32 AM | Web Part Mapping | Web Part:’Wiki text’ of type ‘SharePointPnP.Modernization.WikiTextPart’ is being transformed
9/20/2021 11:52:32 AM | Web Part Mapping | Processing selector functions
9/20/2021 11:52:32 AM | Web Part Mapping | Combining mapping data
9/20/2021 11:52:32 AM | Adding Web Parts to Target Page | Added ‘Client Side Text Web Part’ to target page
9/20/2021 11:52:32 AM | Web Part Mapping | Web Part:’Image in wiki text’ of type ‘SharePointPnP.Modernization.WikiImagePart’ is being transformed
9/20/2021 11:52:32 AM | Web Part Mapping | Processing selector functions

**Comment by jansenbe** [comment]
@zwelding : Did you manage to solve your issue? If not then please create a new issue in the PnP Framework repo, will close this one.

**Comment by zwelding** [comment]
I did not. I ended up having to remove all inline images from the original pages.
