### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by myatix** [pnp/modernization#614]
https://github.com/pnp/modernization/tree/master/Solutions/PageTransformationUI/docs/manual%20setup

The link to the SharePoint setup is broken in the readme.md. It looks like the file has been renamed to "OLD" "modernization-ui-manual-sharepoint.old.md".

Is this document not relevant anymore?

**Comment by jansenbe** [comment]
The UI project has been deprecated

**Comment by myatix** [comment]
Okay? Can you be more specific? 
Does it still work? 
Is there an alternative solution with similar functionality?

Any further information would be appreciated! :)
