### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jacob-tornqvist** [pnp/modernization#615]
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

This is probably not right. The expected return value for property AutoPlay should be of type boolean.

[Link to line](https://github.com/pnp/modernization/blame/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework.Tests/Transform/Publishing/webpartmapping.xml#L307)

**Comment by jansenbe** [comment]
@jacob-tornqvist : you can always update the webpartmapping.xml file and use the updated mapping. Did you manage to solve your issue? If not then please create a new issue in the PnP Framework repo, will close this one.
