### ISSUE TITLE
LVWP for certain list templates is not converted

### ISSUE THREAD

**Issue by hawaiianmetal** [pnp/modernization#616]
#### Problem Area

[ X ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Modern list web web part is created on modern page.

#### Observed Behavior

The list web part on a modern page is not created. On the page, the following text is displayed: ***Web part Announcements was not transformed***. In the verbose log file, this appears as a warning (detailed log shown below).

12/7/2021 9:38:32 AM  |  /Pages/testpage.aspx  |   Content Transform  |  Not Supported, Non Exportable or Unidentified Web Part

Note that only seems to occur with this combination of factors:

1. If you have a publishing page (I only tested from SP2016), and 
2. The page layout is one that has zones (I tested Blank Web Part page), and 
3. You have certain legacy list templates. I can repro consistently with Announcements, Contacts and Links

#### Steps to Reproduce

1. Create a new publishing portal site collection in SP2016 (SP2013 is probably the same but I didn't test)
2. Active web-scoped feature Team Collaboration Lists
3. Create a new Announcements list
4. Create a new publishing page based on the Blank Web Part page layout
5. Edit new page and add the announcements list to any zone on the page
6. Create new communication site in SPOL
7. Convert the page

ConvertTo-PnPPage -Identity "testpage.aspx" -PublishingPage -Overwrite -TargetConnection $targetConn -Connection $sourceConn  -LogType File -LogFolder c:\temp -LogVerbose

#### Software versions

PnP.PowerShell 1.8.0
SharePointPnPPowerShell2016  3.29.2101.0
SharePointPnP.Modernization.Framework.dll  1.0.2012.0

#### Verbose log output (URLs have been sanitized)

# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
12/7/2021 9:38:24 AM  |  00:00:13  |  [/Pages/testpage.aspx](https://in.domain.com/sites/migrationtest3/Pages/testpage.aspx)  |  [/SitePages/testpage.aspx](https://name.sharepoint.us/sites/MigrationTest15/SitePages/testpage.aspx)  |  Successful with 1 warnings and 0 non-critical errors
## Warnings during transformation

Date  |  Source Page  |  Operation  |  Message
-------------  |  -------------  |  -------------  |  -------------
12/7/2021 9:38:32 AM  |  /Pages/testpage.aspx  |   Content Transform  |  Not Supported, Non Exportable or Unidentified Web Part
# Individual Page details
## Transformation Details: /Pages/testpage.aspx

- Report date: 12/7/2021 9:38:24 AM
- Transform duration: 00:00:13
- Transforming from site: https://in.domain./sites/migrationtest3
- Cross-Site transfer mode to site: https://name.sharepoint.us/sites/MigrationTest15
- Transforming page: /sites/migrationtest3/Pages/testpage.aspx
- Source SharePoint version:  2016 (16.0.0.5227)
- Mode:  Publishing Page Transformation Mode
- Transformed Page: /sites/MigrationTest15/SitePages/testpage.aspx

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.7.3.0
Overwrite   |   True
Target Page Name   |   
Target Page Folder   |   
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   False
Publish Created Page   |   True
Post As News   |   False
Disable Page Comments   |   False
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   
Skip Hidden Web Parts   |   False
Term Mapping File   |   
Skip Term Store Mapping   |   False
Skip User Mapping   |   False
User Mapping File   |   
L D A P Connection String   |   
Skip Telemetry   |   False
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
12/7/2021 9:38:25 AM  |  _Input Validation_  |  _Validation checks complete_
12/7/2021 9:38:25 AM  |  _SharePoint Connection_  |  _Loading client context objects_
12/7/2021 9:38:26 AM  |  _SharePoint Connection_  |  _Loading target client context object_
12/7/2021 9:38:26 AM  |  _Page Creation_  |  _Detect if the page is living inside a folder_
12/7/2021 9:38:26 AM  |  Page Creation  |  In Cross-Site transform mode the original source file name is used
12/7/2021 9:38:26 AM  |  _Page Creation_  |  _Just try to load the page in the fastest possible manner, we only want to see if the page exists or not_
12/7/2021 9:38:28 AM  |  Load  |  Page does not exist in current web
12/7/2021 9:38:28 AM  |  Page Creation  |  Checking Page Exists
12/7/2021 9:38:29 AM  |  Page Creation  |  Modern page created 
12/7/2021 9:38:29 AM  |  Article page handling  |  Transforming source page as Article page
12/7/2021 9:38:29 AM  |  Article page handling  |  Recognized source page as a Publishing Page - Analyzing web parts and page layouts
12/7/2021 9:38:29 AM  |  Page Layout Manager  |  Page uses BlankWebPartPage as page layout, mapping that will be used is BlankWebPartPage
12/7/2021 9:38:30 AM  |  Content Transform  |  Calling Web Services to Extract Web Parts from Page
12/7/2021 9:38:32 AM  |  **Content Transform**  |  **Not Supported, Non Exportable or Unidentified Web Part**
12/7/2021 9:38:32 AM  |  Content Transform  |  Source page contains web part `Announcements` of type `Unsupported Web Part Type`
12/7/2021 9:38:32 AM  |  Article page handling  |  Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
12/7/2021 9:38:32 AM  |  Set Page Title  |  Setting the modern page title: Testpage
12/7/2021 9:38:32 AM  |  _Article page handling_  |  _Preparing content transformation_
12/7/2021 9:38:32 AM  |  Article page handling  |  Transforming content
12/7/2021 9:38:32 AM  |  Content Transform  |  Transforming web parts
12/7/2021 9:38:33 AM  |  Web Part Mapping  |  Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
12/7/2021 9:38:33 AM  |  _Web Part Mapping_  |  _Processing selector functions_
12/7/2021 9:38:33 AM  |  _Web Part Mapping_  |  _Combining mapping data_
12/7/2021 9:38:33 AM  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
12/7/2021 9:38:33 AM  |  Web Part Mapping  |  Web Part:'Announcements' of type 'Unsupported Web Part Type' is being transformed
12/7/2021 9:38:33 AM  |  _Web Part Mapping_  |  _Combining mapping data_
12/7/2021 9:38:33 AM  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
12/7/2021 9:38:33 AM  |  Content Transform  |  Transforming web parts complete
12/7/2021 9:38:33 AM  |  Article page handling  |  Transforming content complete
12/7/2021 9:38:33 AM  |  Page Layout Manager  |  Page uses BlankWebPartPage as page layout, mapping that will be used is BlankWebPartPage
12/7/2021 9:38:33 AM  |  _User Transform_  |  _Principal Input:username
12/7/2021 9:38:33 AM  |  User Transform  |  Not remapping user username
12/7/2021 9:38:34 AM  |  Remove Empty Text Parts  |  Removing empty text web part
12/7/2021 9:38:34 AM  |  Article page handling  |  Saved page in cross-site collection: testpage.aspx
12/7/2021 9:38:35 AM  |  Item level permissions  |  Item level permissions read
12/7/2021 9:38:38 AM  |  Page Creation  |  Transformation Complete

**Comment by jansenbe** [comment]
@hawaiianmetal : what you see is expected, for certain list view web part usages there's no equivalent modern experience, hence there's no transformation.
