### ISSUE TITLE
Not Supported??? 

### ISSUE THREAD

**Issue by myatix** [pnp/modernization#617]
I understand that this solution is no longer supported?

Is there an alternative to this solution?

Using an Azure Function and allowing users to upgarde their own pages is a genius idea but PnP.Powershell has now been updated and it would be great to know what the new solutions to modernizing classic pages is?

Hope someone can assist?

**Comment by jansenbe** [comment]
Page transformation is still there, it just moved into pnp framework. PnP PowerShell uses it from there
